// <auto-generated />
using System;
using FoldrengesekSOE2026.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoldrengesekSOE2026.Migrations
{
    [DbContext(typeof(FoldrengesContext))]
    partial class FoldrengesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoldrengesekSOE2026.Models.Naplo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Ido")
                        .HasColumnType("time");

                    b.Property<double>("Intenzitas")
                        .HasColumnType("float");

                    b.Property<double>("Magnitudo")
                        .HasColumnType("float");

                    b.Property<int>("TelepulesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TelepulesID");

                    b.ToTable("Naplok");
                });

            modelBuilder.Entity("FoldrengesekSOE2026.Models.Telepules", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varmegye")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Telepulesek");
                });

            modelBuilder.Entity("FoldrengesekSOE2026.Models.Naplo", b =>
                {
                    b.HasOne("FoldrengesekSOE2026.Models.Telepules", "Telepules")
                        .WithMany("Naplok")
                        .HasForeignKey("TelepulesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telepules");
                });

            modelBuilder.Entity("FoldrengesekSOE2026.Models.Telepules", b =>
                {
                    b.Navigation("Naplok");
                });
#pragma warning restore 612, 618
        }
    }
}
